apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv-agent
  namespace: telemetry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tv-agent
  template:
    metadata:
      labels:
        app: tv-agent
    spec:
      containers:
        - name: tv-agent
          image: 029130646645.dkr.ecr.us-east-1.amazonaws.com/tv-bt-agent:latest
          env:
            - name: TV_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BROKERS
              value: "kafka-kafka-bootstrap.telemetry.svc.cluster.local:9092"
            - name: DB_PATH
              value: "/tmp/buffer.db"
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 50m
